package com.example.guevaracabrera.practicando.Modelo;
// Generated 08-oct-2015 18:37:57 by Hibernate Tools 4.foto3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriaempleado generated by hbm2java
 */
@SuppressWarnings("serial")
public class Categoriaempleado implements java.io.Serializable {

    private Integer idCategoria;
    private String nombreCategoria;
    private String descripcion;
    private Set logins = new HashSet(0);

    public Categoriaempleado() {
    }

    public Categoriaempleado(Integer idCategoria, String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }

    public Integer getIdCategoria() {
        return this.idCategoria;
    }

    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }

    public String getNombreCategoria() {
        return this.nombreCategoria;
    }

    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getLogins() {
        return this.logins;
    }

    public void setLogins(Set logins) {
        this.logins = logins;
    }


}


