package com.example.guevaracabrera.practicando.Modelo;
// Generated 08-oct-2015 18:37:57 by Hibernate Tools 4.foto3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mesa generated by hbm2java
 */
@SuppressWarnings("serial")
public class Mesa implements java.io.Serializable {

    private Integer idMesa;
    private String nmesa;
    private String descripcion;
    private Set pedidos = new HashSet(0);

    public Mesa() {
    }

    public Mesa(Integer idMesa, String nmesa, String descripcion) {
        this.idMesa = idMesa;
        this.nmesa = nmesa;
        this.descripcion = descripcion;
    }

    public Mesa(String nmesa, String descripcion) {
        this.nmesa = nmesa;
        this.descripcion = descripcion;
    }

    public Mesa(String nmesa, String descripcion, Set pedidos) {
        this.nmesa = nmesa;
        this.descripcion = descripcion;
        this.pedidos = pedidos;
    }

    public Integer getIdMesa() {
        return this.idMesa;
    }

    public void setIdMesa(Integer idMesa) {
        this.idMesa = idMesa;
    }

    public String getNmesa() {
        return this.nmesa;
    }

    public void setNmesa(String nmesa) {
        this.nmesa = nmesa;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getPedidos() {
        return this.pedidos;
    }

    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }


}


