package com.example.guevaracabrera.practicando.Modelo;
// Generated 08-oct-2015 18:37:57 by Hibernate Tools 4.foto3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
@SuppressWarnings("serial")
public class Pedido  implements java.io.Serializable {

     private Integer idPedido;
     private Empleado empleado;
     private Mesa mesa;
     private double total;
     private boolean estado;
     private boolean estadoCancel;
     private Set detallepedidos = new HashSet(0);
     private Set ventases = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido,Empleado empleado, Mesa mesa, double total, boolean estado, boolean estadoCancel) {
        this.idPedido=idPedido;
        this.empleado = empleado;
        this.mesa = mesa;
        this.total = total;
        this.estado = estado;
        this.estadoCancel = estadoCancel;
    }
    public Pedido(Empleado empleado, Mesa mesa, double total, boolean estado, boolean estadoCancel, Set detallepedidos, Set ventases) {
       this.empleado = empleado;
       this.mesa = mesa;
       this.total = total;
       this.estado = estado;
       this.estadoCancel = estadoCancel;
       this.detallepedidos = detallepedidos;
       this.ventases = ventases;
    }

    public Pedido(Mesa mesas, Empleado empleado, double total) {
        this.empleado = empleado;
        this.mesa = mesas;
        this.total = total;
    }

    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public double getTotal() {

        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public boolean isEstadoCancel() {
        return this.estadoCancel;
    }
    
    public void setEstadoCancel(boolean estadoCancel) {
        this.estadoCancel = estadoCancel;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }
    public Set getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set ventases) {
        this.ventases = ventases;
    }


}


