package com.example.guevaracabrera.practicando.Modelo;
// Generated 08-oct-2015 18:37:57 by Hibernate Tools 4.foto3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoplato generated by hbm2java
 */
public class Tipoplato implements java.io.Serializable {

    private Integer idTipo;
    private String nombreTipo;
    private String descripcion;
    private String imagen;
    private Set platos = new HashSet(0);

    public Tipoplato() {
    }

    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public Tipoplato(Integer idTipo, String nombreTipo, String descripcion) {
        this.idTipo = idTipo;
        this.nombreTipo = nombreTipo;
        this.descripcion = descripcion;
    }

    public Integer getIdTipo() {
        return this.idTipo;
    }

    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }

    public String getNombreTipo() {
        return this.nombreTipo;
    }

    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getPlatos() {
        return this.platos;
    }

    public void setPlatos(Set platos) {
        this.platos = platos;
    }

    @Override
    public String toString() {
        return nombreTipo;
    }
}


