package com.uss.GuevaraMonsalveBernal.Proyecto.Modelo;
// Generated 08-oct-2015 18:37:57 by Hibernate Tools 4.foto3.1


/**
 * SelecionMesa generated by hbm2java
 */
@SuppressWarnings("serial")
public class Login implements java.io.Serializable {

    private Integer idLogeo;
    private Categoriaempleado categoriaempleado;
    private Empleado empleado;
    private boolean estado;

    public Login() {
    }

    public Login(Integer idLogeo,  Empleado empleado,Categoriaempleado categoriaempleado) {
        this.idLogeo = idLogeo;
        this.categoriaempleado = categoriaempleado;
        this.empleado = empleado;
    }

    public Login(Categoriaempleado categoriaempleado, Empleado empleado, boolean estado) {
        this.categoriaempleado = categoriaempleado;
        this.empleado = empleado;
        this.estado = estado;
    }

    public Integer getIdLogeo() {
        return this.idLogeo;
    }

    public void setIdLogeo(Integer idLogeo) {
        this.idLogeo = idLogeo;
    }

    public Categoriaempleado getCategoriaempleado() {
        return this.categoriaempleado;
    }

    public void setCategoriaempleado(Categoriaempleado categoriaempleado) {
        this.categoriaempleado = categoriaempleado;
    }

    public Empleado getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }


}


