package com.uss.GuevaraMonsalveBernal.Proyecto.Modelo;
// Generated 08-oct-2015 18:37:57 by Hibernate Tools 4.foto3.1


import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {

     private Integer idVentas;
     private Pedido pedido;
     private String ndocumento;
     private double totalPagado;
     private double total;
     private double vuelto;
     private Date fecha;
     private boolean estado;

    public Ventas() {
    }

    public Ventas(Pedido pedido, String ndocumento, double totalPagado, double total, double vuelto, Date fecha, boolean estado) {
       this.pedido = pedido;
       this.ndocumento = ndocumento;
       this.totalPagado = totalPagado;
       this.total = total;
       this.vuelto = vuelto;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public Integer getIdVentas() {
        return this.idVentas;
    }
    
    public void setIdVentas(Integer idVentas) {
        this.idVentas = idVentas;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getNdocumento() {
        return this.ndocumento;
    }
    
    public void setNdocumento(String ndocumento) {
        this.ndocumento = ndocumento;
    }
    public double getTotalPagado() {
        return this.totalPagado;
    }
    
    public void setTotalPagado(double totalPagado) {
        this.totalPagado = totalPagado;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public double getVuelto() {
        return this.vuelto;
    }
    
    public void setVuelto(double vuelto) {
        this.vuelto = vuelto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


